### ISSUE TITLE
White square produces an UIError

### ISSUE THREAD

**Issue by braincomb** [ESOUIMods/HarvestMap#2]
Strange solid white square appears in top-left corner, which when hovering over produces the following UIError:

```
user:/AddOns/HarvestMap/Libs/LibMainMenu/LibMainMenu.lua:69: function expected instead of nil
stack traceback:
user:/AddOns/HarvestMap/Libs/LibMainMenu/LibMainMenu.lua:69: in function '(anonymous)'
```

Using version 3.14.10.

**Comment by Sharlikran** [comment]
I asked Shinni if I could put this on GitHub because it's just a preference and I like to keep track of my changes. I do not develop with Shinni and if you still have that issue you should explain this to him in his comments section. If he does not respond or declines the request that is up to him. Sorry for any confusion.
