### ISSUE TITLE
HarvestMap not working out of base game zones

### ISSUE THREAD

**Issue by SugarDroid** [ESOUIMods/HarvestMap#4]
@Sharlikran Whenever I go out of these zones an error pop up on the screen. 

![image](https://user-images.githubusercontent.com/56313144/104805413-f7140d80-57d1-11eb-8d62-3442348e45f2.png)

**Comment by Sharlikran** [comment]
I have this here because I nitpick at the code depending on the author's changes. Currently I am have not had to make any slight alterations to the code.

This is hosted with permission from the author but the only difference is that I do not embed the required libraries and place them in the libs folder.

The author does not read this so I recomend using the comments section. 

I do not understand the author's code well enough to know why you experience the issue you are reporting as I don't have any issues in any zones.
