### ISSUE TITLE
Linux script

### ISSUE THREAD

**Issue by StevenAn1213** [ESOUIMods/HarvestMap#8]
echo "Enter your home folder (for example: /home/john/)"
read home

if [[ "$home" =~ ^\/[a-zA-Z]*\/[a-zA-Z]*\/$ ]]; then

BasePath="$home.steam/steam/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/My Documents/Elder Scrolls Online/live"
HarvestMapPath="$BasePath/AddOns/HarvestMapData/"
SavedVariablesPath="$BasePath/SavedVariables/"
EmptySaveFile="$HarvestMapPath/Main/emptyTable.lua"

echo "Starting downloads from DB..."

for module in AD EP DC DLC NF
do
SavedVariable="HarvestMap$module"
SavedVariableFile="$SavedVariablesPath/$SavedVariable.lua"

cp "$SavedVariableFile" "$SavedVariablesPath/$SavedVariable-backup.lua"

SavedVariableBackup="$SavedVariablesPath/$SavedVariable-backup.lua"
OutputFile="$HarvestMapPath/Modules/HarvestMap$module/HarvestMap$module.lua"

echo "Downloading $module..."

curl -s -d "@$SavedVariableBackup" -X POST http://harvestmap.binaryvector.net:8081 -o "$OutputFile"
done

echo "Files downloaded!"

else

echo "Wrong folder input, try again..."

fi

**Comment by Sharlikran** [comment]
I have permission to have any of Shini's repositories on Github because I asked, but I do not have access to upload changes to ESOUI. However, he also does not use my personal changes. He is a nice guy so I'm not saying he would not use something a user suggests though.

This is also true for other authors. For some authors there is a license with their mod. For other mods I made the repository when I first started modding again a few years ago because I had removed LibStub but they chose not to use my changes.

I don't go around advertising people download from my Github. I don't want to have to mark them all private.

If it is a mod I maintain and my name appears in the list of authors or contributors then I don't mind. Otherwise, I would prefer you not use my GitHub out of convenience to make a pull request or suggest changes when the author doesn't have their own GitHub.

Contact the author directly through a PM or by posting in their comments section without using one of my repositories and ask them your question directly.
